import Head from "next/head";
import Image from "next/image";
import { AppShell, Center, Divider, Navbar, Text } from "@mantine/core";
import dwight from "../../public/7.svg";
import Accounts from "@/components/Accounts";
import AccountInfo from "@/components/AccountInfo";
import { useEffect, useReducer, useState } from "react";
import { initialState } from "@/components/reducer";
import { useQuery } from "../../convex/_generated/react";

export default function Home() {
  // const [state, dispatch] = useReducer(reducer, initialState);
  const [currentAccount, setCurrentAccount] = useState(initialState[0]);
  const data = useQuery("listAccounts");
 console.log('data', data)

  return (
    <>
      <Head>
        <title>Dwight Warden</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppShell
        padding="md"
        navbar={
          <Navbar width={{ base: 200 }} height={"100%"} p="xs">
            <Navbar.Section>
              <Center style={{ padding: 18 }}>
                <Image
                  alt="picture of dwight shruttes face"
                  src={dwight}
                  width={100}
                  height={100}
                />
              </Center>
            </Navbar.Section>
            <Divider />
            <Text></Text>
            <Accounts
              userAccounts={initialState}
              currentAccount={currentAccount}
              setCurrentAccount={setCurrentAccount}
            />
          </Navbar>
        }
        // header={
        //   <Header height={60} p="xs">
        //     {/* Header content */}
        //     What is this
        //   </Header>
        // }
        styles={(theme) => ({
          main: {
            backgroundColor:
              theme.colorScheme === "dark"
                ? theme.colors.dark[8]
                : theme.colors.gray[0],
          },
        })}
      >
        <AccountInfo currentAccount={data} />
      </AppShell>
    </>
  );
}
