import Head from "next/head";
import Image from "next/image";
import { AppShell, Center, Divider, Navbar, Text } from "@mantine/core";
import dwight from "../../public/7.svg";
import Accounts from "@/components/Accounts";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Dwight Warden</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppShell
        padding="md"
        navbar={
          <Navbar width={{ base: 250 }} height={"100%"} p="xs">
            <Navbar.Section>
              <Center style={{padding: 18}}>
                <Image
                  alt="picture of dwight shruttes face"
                  src={dwight}
                  width={100}
                  height={100}
                />
              </Center>
            </Navbar.Section>
            <Divider />
            <Accounts />
          </Navbar>
        }
        // header={
        //   <Header height={60} p="xs">
        //     {/* Header content */}
        //     What is this
        //   </Header>
        // }
        styles={(theme) => ({
          main: {
            backgroundColor:
              theme.colorScheme === "dark"
                ? theme.colors.dark[8]
                : theme.colors.gray[0],
          },
        })}
      >
        {/* Your application here */}
      </AppShell>
    </>
  );
}
