import Head from "next/head";
import Image from "next/image";
import { AppShell, Button, Center, Divider, Navbar } from "@mantine/core";
import dwight from "../../public/7.svg";
import Accounts from "@/components/Accounts";
import AccountInfo from "@/components/AccountInfo";
import { useEffect, useState } from "react";
import { useQuery } from "../../convex/_generated/react";

export default function Home() {
  const [inputsDisabled, setInputsDisabled] = useState(true);

  const data = useQuery("listAccounts") || [
    { name: "", username: "", password: "", id: "", url: "" },
  ];
  const [currentAccount, setCurrentAccount] = useState({
    name: "",
    username: "",
    password: "",
    id: "",
    url: "",
  });
  const createNewAccount = () => {
    setCurrentAccount({
      name: "",
      username: "",
      password: "",
      id: "",
      url: "",
    });
    setInputsDisabled(false);
  };

  useEffect(() => setCurrentAccount(data[0]), []);
  return (
    <>
      <Head>
        <title>Dwight Warden</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppShell
        padding="md"
        navbar={
          <Navbar width={{ base: 200 }} height={"100%"} p="xs">
            <Navbar.Section>
              <Center style={{ padding: 18 }}>
                <Image
                  alt="picture of dwight shruttes face"
                  src={dwight}
                  width={100}
                  height={100}
                  priority
                />
              </Center>
            </Navbar.Section>
            <Divider style={{ marginBottom: 10 }} />
            <Center>
              <Button
                variant="gradient"
                gradient={{ from: "teal", to: "lime", deg: 105 }}
                onClick={createNewAccount}
              >
                Add account
              </Button>
            </Center>
            <Accounts setCurrentAccount={setCurrentAccount} />
          </Navbar>
        }
        styles={(theme) => ({
          main: {
            backgroundColor:
              theme.colorScheme === "dark"
                ? theme.colors.dark[8]
                : theme.colors.gray[0],
          },
        })}
      >
        <AccountInfo
          currentAccount={currentAccount}
          inputsDisabled={inputsDisabled}
          setInputsDisabled={setInputsDisabled}
        />
      </AppShell>
    </>
  );
}
